#!/usr/bin/env bash
# installs nginx and conifgures it to serve a page with a unique id

sudo apt-get -y updare && sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'



# Create the index.html file
#echo "<h1>Hello World!</h1>" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Check if the default file already exists
# if [ -f /etc/nginx/sites-available/default ]
# then
#   # Rename the existing default file to default_old
#   sudo mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default_old
# fi

# # Create a new server block for Nginx
# sudo bash -c 'cat << EOF > /etc/nginx/sites-available/default
# server {
#     listen 80 default_server;
#     listen [::]:80 default_server;

#     root /var/www/html/index.nginx-debian.html;
#     index index.html index.htm index.nginx-debian.html;

#     location / {
#         try_files \$uri \$uri/ =404;
#     }

#     location = / {
#         echo "Hello World!";
#     }
# }
# EOF'

# #return *****go through error ****
# ip_address=$(hostname -I | awk '{print $1}')
# text="localhost"
# sed -i "s/\b\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\b/$ip_address/g" /etc/hosts
# echo "$ip_address $text" >> /etc/hosts

# # Enable the new server block
# sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

echo 'Hello World!' > /var/www/html/index.html

ip_address=$(hostname -I | awk '{print $1}')
text="localhost"
sed -i "s/\b\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\b/$ip_address/g" /etc/hosts
echo "$ip_address $text" >> /etc/hosts

# Restart Nginx
sudo service nginx restart

service nginx start