#!/usr/bin/env bash
# Install nginx web server

# Stop nginx if it's already running
service nginx stop

# Configure nginx
cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        return 200 "Hello World!";
    }
}
EOF

# Start nginx
/usr/sbin/nginx