#!/usr/bin/env bash
# installs nginx and conifgures it to serve a page with a unique id

sudo apt-get -y updare && sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.nginx-debian.html
service nginx start