#!/usr/bin/env bash
# this script resolves localhost to *0.2 and facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/^.*localhost$/127.0.0.2\tlocalhost/g' ~/hosts.new
sed -i 's/^.*facebook.com$/8.8.8.8\tfacebook.com/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
