#!/usr/bin/env bash
#This script manages process

#!/usr/bin/env bash

PIDFILE=/var/run/my_process.pid
SCRIPTNAME=manage_my_process

start() {
    if [ -f $PIDFILE ]; then
        echo "$SCRIPTNAME is already running."
    else
        echo "Starting $SCRIPTNAME"
        /bin/bash /tmp/my_process &
        echo $! > $PIDFILE
        echo "$SCRIPTNAME started"
    fi
}

stop() {
    if [ -f $PIDFILE ]; then
        PID=$(cat $PIDFILE)
        echo "Stopping $SCRIPTNAME"
        kill $PID
        rm $PIDFILE
        echo "$SCRIPTNAME stopped"
    else
        echo "$SCRIPTNAME is not running."
    fi
}

restart() {
    stop
    start
    echo "$SCRIPTNAME restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
