#!/usr/bin/env bash
# display /etc/passwd contents

while IFS=':' read -r username _ uid _ _ homedir _; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $homedir"
done < /etc/passwd