#!/usr/bin/env bash
#displays contents of etc/passwd

while IFS=':' read -r username password uid gid _ shell; do
    IFS='/' read -r home_dir default_shell <<< "$shell"
    echo "The user $username is part of the $gid gang, lives in $home_dir and rides $default_shell. User ID's place is protected by the passcode $password, more info about the user here: $uid"
done < /etc/passwd