#!/usr/bin/env bash
#displays contents of etc/passwd

# Read the file /etc/passwd line by line
#!/bin/bash

#!/bin/bash

while IFS=':' read -r username password gid info homedir shell; do
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
