#!/usr/bin/env bash
#displays contents of etc/passwd

while IFS=: read -r username pass uid gid info homedir shell; do
  IFS=';' read -r -a uid_info <<< "$info"
  password=${pass:-x}
  echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: ${uid_info[0]}"
done < "/etc/passwd"